### ISSUE TITLE
app not working is macos 15.0 beta

### ISSUE THREAD

**Issue by Chahal29** [gmshrek/mouse-boost#15]
There is not option showing up in system preference extension for mouseboost pro. plz help

**Comment by gmshrek** [comment]
Execute the following command:

pluginkit -e "use" -i com.shrek.rightmouse.extension



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2024 13:39 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [gmshrek/mouse-boost] app not working is macos 15.0 beta (Issue #15) |

There is not option showing up in system preference extension for mouseboost pro. plz help

**Comment by Chahal29** [comment]
Bro thanks now its working but now iam having another issue.
I have selected the over ride system right click option... 

Sometimes when i right click on some files and folders i get this right click menu
![Screenshot - 2024-08-31 12 03 32](https://github.com/user-attachments/assets/8a98d92a-70a2-45c5-893c-602fa0664cc8)

And othertimes it shows this type of menu
![Screenshot - 2024-08-31 12 03 39](https://github.com/user-attachments/assets/82211929-8c2e-4fcd-94d3-fc60aff0152c)

plz help

**Comment by Chahal29** [comment]
And another issue is that i select multiple file and press right on them also i get this menu only

![Screenshot - 2024-08-31 12 22 18](https://github.com/user-attachments/assets/7115cdd3-ba8b-4455-bc66-49e022008447)

plz help

**Comment by gmshrek** [comment]
The menu displayed when you select the desktop is different from when you select other files or folders!
You can try not to use the shortcut, override the right-click option to remove, the operation is better



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2024 14:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] app not working is macos 15.0 beta (Issue #15) |

And another issue is that i select multiple file and press right on them also i get this menu only

Screenshot.-.2024-08-31.12.22.18.png (view on web)

plz help

**Comment by Chahal29** [comment]
ok bro. thanks for the app i love this app.... I hope in future updates this override the right click option works fine. thanks

**Comment by gmshrek** [comment]
OK，Thanks for your feedback.


| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2024 15:45 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] app not working is macos 15.0 beta (Issue #15) |

ok bro. thanks for the app i love this app.... I hope in future updates this override the right click option works fine. thanks
