### ISSUE TITLE
'Folder Icon' changes fail if Icon has already been set

### ISSUE THREAD

**Issue by jluby** [gmshrek/mouse-boost#2]

**Comment by gmshrek** [comment]
Hello, try again after upgrading to 3.1.0 



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 05/3/2023 00:23 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [gmshrek/mouse-boost] 'Folder Icon' changes fail if Icon has already been set (Issue #2) |

**Comment by jluby** [comment]
Hi, I am up to date. It is still not working.

**Comment by jluby** [comment]
Hm, false alarm. It looks like it works but sometimes requires me to close out and reopen to register the change visually.

I'll close this issue because it may be a problem with my system, but potentially worth noting.
