### ISSUE TITLE
iCloud files wont deleted

### ISSUE THREAD

**Issue by JohnnyFireOne** [gmshrek/mouse-boost#8]
hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync,
i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this?
![SCR-20240508-nigh](https://github.com/gmshrek/mouse-boost/assets/136648679/3dac166c-745b-44a0-afc3-e67efa18f231)

**Comment by gmshrek** [comment]
Hello,

To prevent further syncing of your files in iCloud, you can turn off iCloud Drive. However, please be aware that this action will affect all apps using iCloud Drive, potentially leading to the deletion or desynchronization of data saved by other apps.

Before proceeding, ensure you have backed up any important data to avoid loss.

Here's how to turn off iCloud Drive:

Open the "Settings" app on your device.
Tap on your name to access iCloud settings.
Tap "iCloud."
Find "iCloud Drive" in the list of apps and toggle the switch off.

Please note that currently, we do not support disabling iCloud syncing for individual apps without affecting others. We value your feedback and will consider it for future updates.

Thank you for your understanding.



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/8/2024 20:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync,
i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this?
SCR-20240508-nigh.png (view on web)

**Comment by JohnnyFireOne** [comment]
Hello this is kit a solution, other app can sync and unsync without issue I need the iCloud Drive enable, all I want is the erase the better mouse pro data from iCloud that keeps restored to my Mac every time without the app installed8 Μαΐ 2024, 17:51, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿
Hello,

To prevent further syncing of your files in iCloud, you can turn off iCloud Drive. However, please be aware that this action will affect all apps using iCloud Drive, potentially leading to the deletion or desynchronization of data saved by other apps.

Before proceeding, ensure you have backed up any important data to avoid loss.

Here's how to turn off iCloud Drive:

Open the "Settings" app on your device.
Tap on your name to access iCloud settings.
Tap "iCloud."
Find "iCloud Drive" in the list of apps and toggle the switch off.

Please note that currently, we do not support disabling iCloud syncing for individual apps without affecting others. We value your feedback and will consider it for future updates.

Thank you for your understanding.



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/8/2024 20:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync,
i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this?
SCR-20240508-nigh.png (view on web)

**Comment by gmshrek** [comment]
Hello, we will provide an operation to delete in the app later



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/8/2024 22:56 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Hello this is kit a solution, other app can sync and unsync without issue I need the iCloud Drive enable, all I want is the erase the better mouse pro data from iCloud that keeps restored to my Mac every time without the app installed8 Μαΐ 2024, 17:51, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿
Hello,

To prevent further syncing of your files in iCloud, you can turn off iCloud Drive. However, please be aware that this action will affect all apps using iCloud Drive, potentially leading to the deletion or desynchronization of data saved by other apps.

Before proceeding, ensure you have backed up any important data to avoid loss.

Here's how to turn off iCloud Drive:

Open the "Settings" app on your device.
Tap on your name to access iCloud settings.
Tap "iCloud."
Find "iCloud Drive" in the list of apps and toggle the switch off.

Please note that currently, we do not support disabling iCloud syncing for individual apps without affecting others. We value your feedback and will consider it for future updates.

Thank you for your understanding.



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/8/2024 20:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync,
i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this?
SCR-20240508-nigh.png (view on web)

**Comment by JohnnyFireOne** [comment]
> Hello, we will provide an operation to delete in the app later | | gmshrek | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | Johnny ***@***.***> | | Date | 05/8/2024 22:56 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) | Hello this is kit a solution, other app can sync and unsync without issue I need the iCloud Drive enable, all I want is the erase the better mouse pro data from iCloud that keeps restored to my Mac every time without the app installed8 Μαΐ 2024, 17:51, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿ Hello, To prevent further syncing of your files in iCloud, you can turn off iCloud Drive. However, please be aware that this action will affect all apps using iCloud Drive, potentially leading to the deletion or desynchronization of data saved by other apps. Before proceeding, ensure you have backed up any important data to avoid loss. Here's how to turn off iCloud Drive: Open the "Settings" app on your device. Tap on your name to access iCloud settings. Tap "iCloud." Find "iCloud Drive" in the list of apps and toggle the switch off. Please note that currently, we do not support disabling iCloud syncing for individual apps without affecting others. We value your feedback and will consider it for future updates. Thank you for your understanding. | | gmshrek | | ***@***.*** |
> ---- Replied Message ---- | From | Johnny ***@***.***> | | Date | 05/8/2024 20:04 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) | hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync, i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this? SCR-20240508-nigh.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

hello i test the new version 3.4.6 didn't solve this issue sadly, hope will be fixes soon!

**Comment by bighone** [comment]
System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost

![image](https://github.com/gmshrek/mouse-boost/assets/35794709/732132ad-c832-4b9e-b602-e09248a86bcd)
![image](https://github.com/gmshrek/mouse-boost/assets/35794709/90fd41f6-a456-4c49-9dbd-3f646433cb39)

**Comment by gmshrek** [comment]
Hello:


System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost









| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/13/2024 01:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Hello, we will provide an operation to delete in the app later | | gmshrek | | @.*** |
…
---- Replied Message ---- | From | Johnny @.> | | Date | 05/8/2024 22:56 | | To | @.> | | Cc | @.> , @.> | | Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) | Hello this is kit a solution, other app can sync and unsync without issue I need the iCloud Drive enable, all I want is the erase the better mouse pro data from iCloud that keeps restored to my Mac every time without the app installed8 Μαΐ 2024, 17:51, ο χρήστης «gmshrek @.>» έγραψε:﻿ Hello, To prevent further syncing of your files in iCloud, you can turn off iCloud Drive. However, please be aware that this action will affect all apps using iCloud Drive, potentially leading to the deletion or desynchronization of data saved by other apps. Before proceeding, ensure you have backed up any important data to avoid loss. Here's how to turn off iCloud Drive: Open the "Settings" app on your device. Tap on your name to access iCloud settings. Tap "iCloud." Find "iCloud Drive" in the list of apps and toggle the switch off. Please note that currently, we do not support disabling iCloud syncing for individual apps without affecting others. We value your feedback and will consider it for future updates. Thank you for your understanding. | | gmshrek | | @. |
---- Replied Message ---- | From | Johnny @.> | | Date | 05/8/2024 20:04 | | To | @.> | | Cc | @.> | | Subject | [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) | hello, i have an issue after i disable the settings on iCloud to not sync with the app i uninstall the app and the file still sync, i try to remove em but if icloud is enable keeps syncing even without the app. please can you fix this? SCR-20240508-nigh.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

hello i test the new version 3.4.6 didn't solve this issue sadly, hope will be fixes soon!

**Comment by JohnnyFireOne** [comment]
@gmshrek 

> Hello: System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost | | gmshrek | | ***@***.*** |

hello that didn't exist there, (System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost)

i upload and delete the files from the option of the app but didn't change the folder keep reappear every time

**Comment by bighone** [comment]
Hello, 
That must have something to do with the system. The file must have been deleted.



| |
bighone
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/13/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

@gmshrek

Hello: System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost | | gmshrek | | @.*** |

hello that didn't exist there, (System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost)

i upload and delete the files from the option of the app but didn't change the folder keep reappear every time

**Comment by JohnnyFireOne** [comment]
> Hello, That must have something to do with the system. The file must have been deleted. | | bighone | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | Johnny ***@***.***> | | Date | 05/13/2024 16:36 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) | @gmshrek Hello: System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost | | gmshrek | | @.*** | hello that didn't exist there, (System Settings -> Apple ID -> iCloud -> Manage... -> MouseBoost) i upload and delete the files from the option of the app but didn't change the folder keep reappear every time — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

@gmshrek i tall will apple and they didn’t see anything on their end… they said it must be the from the apps server or something… later I’m gonna make a video to demonstrate the issue better, it’s so annoying that folder restore every time I enable iCloud Drive

**Comment by JohnnyFireOne** [comment]
Version 3.4.7 still didn't fix that at some point it seems but after a while the file restored to the iCloud drive again....
don't know what's going on but its so annoying. its the only app i have this issue and experience it ever.
please take a deeper look if you may i will appreciate it so much!

**Comment by gmshrek** [comment]
Can you send me the full path to the folder you didn't delete?



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/22/2024 04:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Version 3.4.7 still didn't fix that at some point it seems but after a while the file restored to the iCloud drive again....
don't know what's going on but its so annoying. its the only app i have this issue and experience it ever.
please take a deeper look if you may i will appreciate it so much!

**Comment by JohnnyFireOne** [comment]
There is no path, it’s a hidden folder inside iCloud main folder  as you can at screenshots26 Μαΐ 2024, 13:09, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿
Can you send me the full path to the folder you didn't delete?



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/22/2024 04:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Version 3.4.7 still didn't fix that at some point it seems but after a while the file restored to the iCloud drive again....
don't know what's going on but its so annoying. its the only app i have this issue and experience it ever.
please take a deeper look if you may i will appreciate it so much!

**Comment by JohnnyFireOne** [comment]
May that helps?26 Μαΐ 2024, 13:09, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿
Can you send me the full path to the folder you didn't delete?



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/22/2024 04:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Version 3.4.7 still didn't fix that at some point it seems but after a while the file restored to the iCloud drive again....
don't know what's going on but its so annoying. its the only app i have this issue and experience it ever.
please take a deeper look if you may i will appreciate it so much!

**Comment by gmshrek** [comment]
Hello, we checked it carefully, and we don't have permission to handle it.



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/26/2024 20:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

May that helps?26 Μαΐ 2024, 13:09, ο χρήστης «gmshrek ***@***.***>» έγραψε:﻿
Can you send me the full path to the folder you didn't delete?



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 05/22/2024 04:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Version 3.4.7 still didn't fix that at some point it seems but after a while the file restored to the iCloud drive again....
don't know what's going on but its so annoying. its the only app i have this issue and experience it ever.
please take a deeper look if you may i will appreciate it so much!

**Comment by JohnnyFireOne** [comment]
> Hello, we checked it carefully, and we don't have permission to handle it. | | gmshrek | | ***@***.*** |
@gmshrek 

hello, but how? the apps makes the folder and the issue so how is possible not to have the permission to handle it? did you speak with app support to see what's going on? its the only app that gives me this issue.
can you speak with apple as a dev for better control of the issue, cause i done this and they say the issue can be fixed by the
dev of the app, and they didn't see nothing or an issue to my iCloud drive...please proceed more agresive to see whats going on.

**Comment by JohnnyFireOne** [comment]
Sucks to have an issue caused by the app and nothing can happen to fix it.

**Comment by bighone** [comment]
This is not caused by the app, we can't deal with it. You can uninstall it to see if it solves your problem.
We are very sorry.



| |
bighone
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 06/30/2024 18:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Sucks to have an issue caused by the app and nothing can happen to fix it.

**Comment by JohnnyFireOne** [comment]
It’s the app cause it happens only with this app……. I uninstall it but whatever I do the folders keep sync back to my Mac……30 Ιουν 2024, 16:53, ο χρήστης «bighone ***@***.***>» έγραψε:﻿
This is not caused by the app, we can't deal with it. You can uninstall it to see if it solves your problem.
We are very sorry.



| |
bighone
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 06/30/2024 18:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Sucks to have an issue caused by the app and nothing can happen to fix it.

**Comment by gmshrek** [comment]
We are very sorry, we will let the developer continue to troubleshoot the problem.



| |
gmshrek
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 06/30/2024 21:55 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

It’s the app cause it happens only with this app……. I uninstall it but whatever I do the folders keep sync back to my Mac……30 Ιουν 2024, 16:53, ο χρήστης «bighone ***@***.***>» έγραψε:﻿
This is not caused by the app, we can't deal with it. You can uninstall it to see if it solves your problem.
We are very sorry.



| |
bighone
|
|
***@***.***
|


---- Replied Message ----
| From | Johnny ***@***.***> |
| Date | 06/30/2024 18:30 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |

Sucks to have an issue caused by the app and nothing can happen to fix it.

**Comment by JohnnyFireOne** [comment]
> We are very sorry, we will let the developer continue to troubleshoot the problem.
> 
> 
> 
> | |
> gmshrek
> |
> |
> ***@***.***
> |
> 
> 
> ---- Replied Message ----
> | From | Johnny ***@***.***> |
> | Date | 06/30/2024 21:55 |
> | To | ***@***.***> |
> | Cc | ***@***.***> ,
> ***@***.***> |
> | Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |
> 
> It’s the app cause it happens only with this app……. I uninstall it but whatever I do the folders keep sync back to my Mac……30 Ιουν 2024, 16:53, ο χρήστης «bighone ***@***.***>» έγραψε:﻿
> This is not caused by the app, we can't deal with it. You can uninstall it to see if it solves your problem.
> We are very sorry.
> 
> 
> 
> | |
> bighone
> |
> |
> ***@***.***
> |
> 
> 
> ---- Replied Message ----
> | From | Johnny ***@***.***> |
> | Date | 06/30/2024 18:30 |
> | To | ***@***.***> |
> | Cc | ***@***.***> ,
> ***@***.***> |
> | Subject | Re: [gmshrek/mouse-boost] iCloud files wont deleted (Issue #8) |
> 
> Sucks to have an issue caused by the app and nothing can happen to fix it.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Need to speak with Apple to fix this issue.....
